
[mediapool "bucket"]

    name = mp-store

[bucket "mp-store"]

    url = https://a.b.com/xyz?region=sz&bucket=bname&security-token=abc
    name = mp-store
    driver = aliyun-oss
    access-key-id = 0
    access-key-secret = 0

[server "http"]
    port = 7309

