# src/server


[bucket "mp-store"]
    url = https://a.b.com/xyz?region=sz&bucket=bname&security-token=abc
    name = mp-store
    driver = aliyun-oss
    access-key-id = 0
    access-key-secret = 0

[buckets-driver "tencent-cos"]
    enabled = 1
    priority = 0


[data]
    groups = mpool

[datagroup "mpool"]
    alias = mpool
    enabled = 1
    uri = uri://starter/data/groups/mpool
    prefix = mpool_
    source = main

    table-name-prefix = mpool_
    datasource = main

[datasource "main"]
    driver = mysql
    name = main
    database = mediapool

    username = mediapool
    password = mediapool


[mediapool "bucket"]
    name = mp-store

[mediapool "cache"]
    dir= ~/.mediapool/cache/

[mediapool "web"]
    objects-base-url = http://localhost:8080/objects/
    max-content-length = 10241024
    min-content-length = 10

[server "http"]
    port = 7309

[server "https"]
    port = 7309
